name: Publish to crates.io

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  tests-and-lints:
    uses: rob2309/spirv-layout/.github/workflows/test-and-lint.yaml@master

  publish:
    name: Publish to crates.io
    needs: [tests-and-lints]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CratesIoToken }}


